---

# Dump diagnostic information.
- import_tasks: diagnostics.yml

# Prepare to install packages.
- import_tasks: pre_install.yml

# Install RPMs from the operating system repositories.
- import_tasks: install.yml

# Bring up services and verify connectivity
- import_tasks: post_install.yml
